'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the 
first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
even-valued terms.
'''

def f(number):
    fibs = [0, 1]
    s = 0
    while 1:
        fibs[0] = fibs[1] + fibs[0]
        fibs[1] = fibs[1] + fibs[0]
        if fibs[0] <= number:
            if fibs[0] % 2 == 0:
                s += fibs[0]
        else:
            break
        if fibs[1] <= number:
            if fibs[1] % 2 == 0:
                s += fibs[1]
        else:
            break
    return s

import cProfile
def test(fun,arg,time=10000):
    for i in range(time):
        fun(arg)
cProfile.run('test(f,4000000)') # total time : 0.099



